global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'python-producer'
    static_configs:
      - targets: ['host.docker.internal:8000']

  - job_name: 'python-consumer'
    static_configs:
      - targets: ['host.docker.internal:8001']
      - targets: ['host.docker.internal:8002'] # if we have multiple consumer instances, we can add them here to scrape their metrics as well.
      - targets: ['host.docker.internal:8003']
      - targets: ['host.docker.internal:8004']
      - targets: ['host.docker.internal:8005']
      - targets: ['host.docker.internal:8006']
      - targets: ['host.docker.internal:8007']
      - targets: ['host.docker.internal:8008']
      - targets: ['host.docker.internal:8009']
      - targets: ['host.docker.internal:8010']
      - targets: ['host.docker.internal:8011']
